add mysql

diff --git a/.github/dev-cicd-aws.yaml b/.github/dev-cicd-aws.yaml
--- a/.github/dev-cicd-aws.yaml
+++ b/.github/dev-cicd-aws.yaml
@@ -1,12 +1,12 @@
-name: istory ci/cd dev pipeline
+ name: istory ci/cd dev pipeline
 
 on:
   push:
-    branches: [ "develop" ]
+    branches: [ "develop"]
   pull_request:
-    branches: [ "develop" ]
+    branches: [ "develop"]
 jobs:
-  verify-pipeline:
+  verify_pipeline:
     environment: runner
     runs-on: ubuntu-latest
     services:
@@ -16,7 +16,7 @@ jobs:
           # root 계정 비밀번호
           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
           # 사용자 계정
-          MYSQL_USER: ${{ secrets.MYSQL_USERNAME }}
+          MYSQL_USER: ${{ secrets.MYSQL_USER }}
           # 사용자 계정 비밀번호
           MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
           # 사용자 계정 데이터베이스
@@ -28,18 +28,26 @@ jobs:
           --health-interval=10s
           --health-timeout=5s
           --health-retries=3
+
     steps:
-    - name: Source Code Checkout
+    - name: 소스코드 다운로드
       uses: actions/checkout@v4 
 
-    - name: Set up JDK 17
+    - name: JDK 17 설치
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
-    - name: Run test java
+    - name: 테스트 수행
       run: ./gradlew test
-    - name: Upload Test Report 테스트코드 써머리에 저장
+
+    - name: 테스트 검사 후 실패 시 파이프라인 중단
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
+
+    - name: 테스트 결과를 STEP Summary 에 업로드
       if: always()
       uses: actions/upload-artifact@v4
       with:
@@ -47,4 +55,4 @@ jobs:
         path: |                    # 여러 경로 지정
           **/build/reports/tests/test/
           **/build/test-results/test/
-        retention-days: 30   
+        retention-days: 30 
